language: ruby
matrix:
  include:
    # see https://www.ruby-lang.org/en/downloads/branches/
    - rvm: ruby-head
    - rvm: 2.6.0
    - rvm: 2.5.3
    - rvm: 2.4.5
    # NOTE: EOL since 2019-03-31
    - rvm: 2.3.8
    # NOTE: EOL since 2018-03-31
    - rvm: 2.2
    # NOTE: EOL since 2017-03-31
    - rvm: 2.1
    # NOTE: EOL since 2016-02-24
    - rvm: 2.0
    # NOTE: JRuby 1.7 is now EOL https://github.com/jruby/jruby/issues/4112#issuecomment-346190422
    - rvm: jruby-1.7
    - rvm: jruby-9.1.17.0
    - rvm: jruby-9.2.5.0
    - rvm: truffleruby
