language: ruby
# NOTE: disabled for now, since it seems to cause issues with the TruffleRuby installation trick
# before_install:
#   # https://stackoverflow.com/a/47972768
#   - gem update --system
#   - gem update bundler
matrix:
  include:
    - rvm: ruby-head
    - rvm: 2.5.1
    - rvm: 2.4.4
    - rvm: 2.3.7
    # NOTE: EOL since 2018-03-31
    - rvm: 2.2
    # NOTE: EOL since 2017-03-31
    - rvm: 2.1
    # NOTE: EOL since 2016-02-24
    - rvm: 2.0
    # NOTE: JRuby 1.7 is now EOL https://github.com/jruby/jruby/issues/4112#issuecomment-346190422
    - rvm: jruby-1.7
    - rvm: jruby-9.1.17.0
    # See https://github.com/oracle/truffleruby/blob/master/doc/user/standalone-distribution.md#testing-truffleruby-in-travisci
    - rvm: system
      install:
        - export TRUFFLERUBY_VERSION=1.0.0-rc6
        - curl -L https://github.com/oracle/truffleruby/releases/download/vm-$TRUFFLERUBY_VERSION/truffleruby-$TRUFFLERUBY_VERSION-linux-amd64.tar.gz | tar xz
        - export PATH="$PWD/truffleruby-$TRUFFLERUBY_VERSION-linux-amd64/bin:$PATH"
        - gem install bundler
        - bundle install
