language: ruby
before_install:
  - gem update bundler
env:
  # required for the yielding runner
  - JRUBY_OPTS=--2.0
rvm:
  - ruby-head
  - 2.4.3
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - jruby-1.7
  - jruby-9.1.15.0
